Add force color option for Salt outputters
saltstack/pepper pull request #237
Opened 2024-04-12 13:10 UTC by Sxderp

The salt CLI commands offer an option to force color output. An option on the Pepper CLI now offers the equivalent feature.

2024-07-29 12:14 UTC, Sxderp commented
@barneysowood is there any activity in this repo? Hopefully this simple change can get merged.

2025-03-19 15:35 UTC, barneysowood requested changes
@Sxderp - thanks for submitting this PR. I'm just getting back to working on this again, apologies for the delay.

This is good and with some slight changes, I'd be happy to merge. I would _ideally_ like to see a test, but if you aren't easily able to do that, no problem - I can pick that up later.

Thanks!

2025-03-19 15:35 UTC, barneysowood commented on pepper/cli.py
> +            ''')
I'd like to have options match the `salt` command where possible:

```bash
    --force-color, --force-colour
                        Force colored output.
```

Would you be OK with updating that to support `--force-color` and `--force-colour`? 
If so, probably best to also update the var to `force_color`

2025-03-25 12:35 UTC, Sxderp commented on pepper/cli.py
> +            ''')
Updated.

2026-06-26 13:22 UTC, closed without merging